//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRESHMusicPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRESHMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string AlbumArtist {
            get {
                return ResourceManager.GetString("AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string Composer {
            get {
                return ResourceManager.GetString("Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Art.
        /// </summary>
        public static string CoverArt {
            get {
                return ResourceManager.GetString("CoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Number.
        /// </summary>
        public static string DiscNumber {
            get {
                return ResourceManager.GetString("DiscNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Files.
        /// </summary>
        public static string FileFilter_AudioFiles {
            get {
                return ResourceManager.GetString("FileFilter_AudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string FileFilter_ImageFiles {
            get {
                return ResourceManager.GetString("FileFilter_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U UTF-8 Playlist.
        /// </summary>
        public static string FileFilter_M3UUTF8 {
            get {
                return ResourceManager.GetString("FileFilter_M3UUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string FileFilter_Other {
            get {
                return ResourceManager.GetString("FileFilter_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Files.
        /// </summary>
        public static string FileFilter_PlaylistFiles {
            get {
                return ResourceManager.GetString("FileFilter_PlaylistFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path or URL.
        /// </summary>
        public static string FilePathOrUrl {
            get {
                return ResourceManager.GetString("FilePathOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also drag and drop to this page..
        /// </summary>
        public static string Import_DragDropHint {
            get {
                return ResourceManager.GetString("Import_DragDropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Folders.
        /// </summary>
        public static string ImportFolders {
            get {
                return ResourceManager.GetString("ImportFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Playlist Files.
        /// </summary>
        public static string ImportPlaylistFiles {
            get {
                return ResourceManager.GetString("ImportPlaylistFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tracks.
        /// </summary>
        public static string ImportTracks {
            get {
                return ResourceManager.GetString("ImportTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue All.
        /// </summary>
        public static string Library_EnqueueAll {
            get {
                return ResourceManager.GetString("Library_EnqueueAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        public static string Library_PlayAll {
            get {
                return ResourceManager.GetString("Library_PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lyrics available.
        /// </summary>
        public static string Lyrics_NoLyrics {
            get {
                return ResourceManager.GetString("Lyrics_NoLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untimed Lyrics.
        /// </summary>
        public static string Lyrics_UntimedLyrics {
            get {
                return ResourceManager.GetString("Lyrics_UntimedLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About FRESHMusicPlayer.
        /// </summary>
        public static string Menu_About_AboutFMP {
            get {
                return ResourceManager.GetString("Menu_About_AboutFMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        public static string Menu_File_NewWindow {
            get {
                return ResourceManager.GetString("Menu_File_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string Menu_GoTo {
            get {
                return ResourceManager.GetString("Menu_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Menu_Playback {
            get {
                return ResourceManager.GetString("Menu_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Menu_Playback_Next {
            get {
                return ResourceManager.GetString("Menu_Playback_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause after current track.
        /// </summary>
        public static string Menu_Playback_PauseAfterCurrentTrack {
            get {
                return ResourceManager.GetString("Menu_Playback_PauseAfterCurrentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string Menu_Playback_PlayPause {
            get {
                return ResourceManager.GetString("Menu_Playback_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Menu_Playback_Previous {
            get {
                return ResourceManager.GetString("Menu_Playback_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Menu_Playback_Repeat {
            get {
                return ResourceManager.GetString("Menu_Playback_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Menu_Playback_Shuffle {
            get {
                return ResourceManager.GetString("Menu_Playback_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Sources.
        /// </summary>
        public static string Menu_TagSources {
            get {
                return ResourceManager.GetString("Menu_TagSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Player.
        /// </summary>
        public static string MiniPlayer {
            get {
                return ResourceManager.GetString("MiniPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t connected to the Internet :(.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Playing.
        /// </summary>
        public static string NothingPlaying {
            get {
                return ResourceManager.GetString("NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared your library!.
        /// </summary>
        public static string Notification_ClearSuccess {
            get {
                return ResourceManager.GetString("Notification_ClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you tried to play, &quot;{0}&quot;, doesn&apos;t seem to exist..
        /// </summary>
        public static string Notification_FileGone {
            get {
                return ResourceManager.GetString("Notification_FileGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the tracks in the playlist doesn&apos;t seem to exist and has been skipped:
        ///{0}.
        /// </summary>
        public static string Notification_FileInPlaylistMissing {
            get {
                return ResourceManager.GetString("Notification_FileInPlaylistMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A playback error occured:
        ///{0}.
        /// </summary>
        public static string Notification_PlaybackError {
            get {
                return ResourceManager.GetString("Notification_PlaybackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for new tracks....
        /// </summary>
        public static string Notification_Scanning {
            get {
                return ResourceManager.GetString("Notification_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string OpenDialog {
            get {
                return ResourceManager.GetString("OpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to top.
        /// </summary>
        public static string PinToTop {
            get {
                return ResourceManager.GetString("PinToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Management.
        /// </summary>
        public static string PlaylistManagement {
            get {
                return ResourceManager.GetString("PlaylistManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do with &quot;{0}&quot;?.
        /// </summary>
        public static string PlaylistManagement_Header {
            get {
                return ResourceManager.GetString("PlaylistManagement_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid name for a playlist..
        /// </summary>
        public static string PlaylistManagement_InvalidName {
            get {
                return ResourceManager.GetString("PlaylistManagement_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Name.
        /// </summary>
        public static string PlaylistManagement_PlaylistName {
            get {
                return ResourceManager.GetString("PlaylistManagement_PlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Management.
        /// </summary>
        public static string QueueManagement {
            get {
                return ResourceManager.GetString("QueueManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string QueueManagement_AddPlaylist {
            get {
                return ResourceManager.GetString("QueueManagement_AddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        public static string QueueManagement_AddTrack {
            get {
                return ResourceManager.GetString("QueueManagement_AddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string QueueManagement_ClearQueue {
            get {
                return ResourceManager.GetString("QueueManagement_ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining:.
        /// </summary>
        public static string QueueManagement_TimeRemaining {
            get {
                return ResourceManager.GetString("QueueManagement_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        public static string RestartNow {
            get {
                return ResourceManager.GetString("RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here to search!.
        /// </summary>
        public static string Search_Prompt {
            get {
                return ResourceManager.GetString("Search_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRESHMusicPlayer Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string Settings_AddFolder {
            get {
                return ResourceManager.GetString("Settings_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Import.
        /// </summary>
        public static string Settings_AutoImport {
            get {
                return ResourceManager.GetString("Settings_AutoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMP will import new tracks from these folders:.
        /// </summary>
        public static string Settings_AutoImport_Info {
            get {
                return ResourceManager.GetString("Settings_AutoImport_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Settings_Automatic {
            get {
                return ResourceManager.GetString("Settings_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me know about new versions of FMP.
        /// </summary>
        public static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and update library.
        /// </summary>
        public static string Settings_CleanLibrary {
            get {
                return ResourceManager.GetString("Settings_CleanLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Settings_ClearAll {
            get {
                return ResourceManager.GetString("Settings_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Squid Grill (and open source contributors).
        /// </summary>
        public static string Settings_Credits {
            get {
                return ResourceManager.GetString("Settings_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Rich Presence.
        /// </summary>
        public static string Settings_IntegrateDiscordRPC {
            get {
                return ResourceManager.GetString("Settings_IntegrateDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Settings_Integrations {
            get {
                return ResourceManager.GetString("Settings_Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under the GPL v3 license.
        /// </summary>
        public static string Settings_License {
            get {
                return ResourceManager.GetString("Settings_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Settings_Maintenance {
            get {
                return ResourceManager.GetString("Settings_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cover art in MPRIS.
        /// </summary>
        public static string Settings_MPRISShowCoverArt {
            get {
                return ResourceManager.GetString("Settings_MPRISShowCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will write files to a temp directory, may make changing tracks take longer.
        /// </summary>
        public static string Settings_MPRISShowCoverArt_Info {
            get {
                return ResourceManager.GetString("Settings_MPRISShowCoverArt_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuke library.
        /// </summary>
        public static string Settings_NukeLibrary {
            get {
                return ResourceManager.GetString("Settings_NukeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to irreversibly clear your library..
        /// </summary>
        public static string Settings_NukeLibrary_Warning {
            get {
                return ResourceManager.GetString("Settings_NukeLibrary_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime Logging.
        /// </summary>
        public static string Settings_PlaytimeLogging {
            get {
                return ResourceManager.GetString("Settings_PlaytimeLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string Settings_Report {
            get {
                return ResourceManager.GetString("Settings_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to default.
        /// </summary>
        public static string Settings_Reset {
            get {
                return ResourceManager.GetString("Settings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMP needs to restart to apply your changes..
        /// </summary>
        public static string Settings_RestartNeeded {
            get {
                return ResourceManager.GetString("Settings_RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time in window title.
        /// </summary>
        public static string Settings_ShowTimeInWindow {
            get {
                return ResourceManager.GetString("Settings_ShowTimeInWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using FRESHMusicPlayer! ❤.
        /// </summary>
        public static string Settings_ThankYou {
            get {
                return ResourceManager.GetString("Settings_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View license.
        /// </summary>
        public static string Settings_ViewLicense {
            get {
                return ResourceManager.GetString("Settings_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View source code.
        /// </summary>
        public static string Settings_ViewSourceCode {
            get {
                return ResourceManager.GetString("Settings_ViewSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMP on the interwebs.
        /// </summary>
        public static string Settings_ViewWebsite {
            get {
                return ResourceManager.GetString("Settings_ViewWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Editor.
        /// </summary>
        public static string TagEditor {
            get {
                return ResourceManager.GetString("TagEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple search results for this album. Which one do you want?.
        /// </summary>
        public static string TagEditor_Disambiguation {
            get {
                return ResourceManager.GetString("TagEditor_Disambiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for this album :(.
        /// </summary>
        public static string TagEditor_NoResults {
            get {
                return ResourceManager.GetString("TagEditor_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Info.
        /// </summary>
        public static string TrackInfo {
            get {
                return ResourceManager.GetString("TrackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Number.
        /// </summary>
        public static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
