//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRESHMusicPlayer.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FRESHMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        public static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        public static string FilePathOrUrl {
            get {
                return ResourceManager.GetString("FilePathOrUrl", resourceCulture);
            }
        }
        
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        public static string ImportFolders {
            get {
                return ResourceManager.GetString("ImportFolders", resourceCulture);
            }
        }
        
        public static string ImportPlaylistFiles {
            get {
                return ResourceManager.GetString("ImportPlaylistFiles", resourceCulture);
            }
        }
        
        public static string ImportTracks {
            get {
                return ResourceManager.GetString("ImportTracks", resourceCulture);
            }
        }
        
        public static string Import_DragDropHint {
            get {
                return ResourceManager.GetString("Import_DragDropHint", resourceCulture);
            }
        }
        
        public static string Library_EnqueueAll {
            get {
                return ResourceManager.GetString("Library_EnqueueAll", resourceCulture);
            }
        }
        
        public static string Library_PlayAll {
            get {
                return ResourceManager.GetString("Library_PlayAll", resourceCulture);
            }
        }
        
        public static string Lyrics {
            get {
                return ResourceManager.GetString("Lyrics", resourceCulture);
            }
        }
        
        public static string Lyrics_NoLyrics {
            get {
                return ResourceManager.GetString("Lyrics_NoLyrics", resourceCulture);
            }
        }
        
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        public static string Menu_About_AboutFMP {
            get {
                return ResourceManager.GetString("Menu_About_AboutFMP", resourceCulture);
            }
        }
        
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        public static string Menu_GoTo {
            get {
                return ResourceManager.GetString("Menu_GoTo", resourceCulture);
            }
        }
        
        public static string Menu_Playback {
            get {
                return ResourceManager.GetString("Menu_Playback", resourceCulture);
            }
        }
        
        public static string Menu_Playback_Next {
            get {
                return ResourceManager.GetString("Menu_Playback_Next", resourceCulture);
            }
        }
        
        public static string Menu_Playback_PauseAfterCurrentTrack {
            get {
                return ResourceManager.GetString("Menu_Playback_PauseAfterCurrentTrack", resourceCulture);
            }
        }
        
        public static string Menu_Playback_PlayPause {
            get {
                return ResourceManager.GetString("Menu_Playback_PlayPause", resourceCulture);
            }
        }
        
        public static string Menu_Playback_Previous {
            get {
                return ResourceManager.GetString("Menu_Playback_Previous", resourceCulture);
            }
        }
        
        public static string Menu_Playback_Repeat {
            get {
                return ResourceManager.GetString("Menu_Playback_Repeat", resourceCulture);
            }
        }
        
        public static string Menu_Playback_Shuffle {
            get {
                return ResourceManager.GetString("Menu_Playback_Shuffle", resourceCulture);
            }
        }
        
        public static string MiniPlayer {
            get {
                return ResourceManager.GetString("MiniPlayer", resourceCulture);
            }
        }
        
        public static string NothingPlaying {
            get {
                return ResourceManager.GetString("NothingPlaying", resourceCulture);
            }
        }
        
        public static string Notification_ClearSuccess {
            get {
                return ResourceManager.GetString("Notification_ClearSuccess", resourceCulture);
            }
        }
        
        public static string Notification_FileGone {
            get {
                return ResourceManager.GetString("Notification_FileGone", resourceCulture);
            }
        }
        
        public static string Notification_FileInPlaylistMissing {
            get {
                return ResourceManager.GetString("Notification_FileInPlaylistMissing", resourceCulture);
            }
        }
        
        public static string Notification_PlaybackError {
            get {
                return ResourceManager.GetString("Notification_PlaybackError", resourceCulture);
            }
        }
        
        public static string Notification_Scanning {
            get {
                return ResourceManager.GetString("Notification_Scanning", resourceCulture);
            }
        }
        
        public static string OpenDialog {
            get {
                return ResourceManager.GetString("OpenDialog", resourceCulture);
            }
        }
        
        public static string PinToTop {
            get {
                return ResourceManager.GetString("PinToTop", resourceCulture);
            }
        }
        
        public static string PlaylistManagement {
            get {
                return ResourceManager.GetString("PlaylistManagement", resourceCulture);
            }
        }
        
        public static string PlaylistManagement_Header {
            get {
                return ResourceManager.GetString("PlaylistManagement_Header", resourceCulture);
            }
        }
        
        public static string PlaylistManagement_InvalidName {
            get {
                return ResourceManager.GetString("PlaylistManagement_InvalidName", resourceCulture);
            }
        }
        
        public static string PlaylistManagement_PlaylistName {
            get {
                return ResourceManager.GetString("PlaylistManagement_PlaylistName", resourceCulture);
            }
        }
        
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        public static string QueueManagement {
            get {
                return ResourceManager.GetString("QueueManagement", resourceCulture);
            }
        }
        
        public static string QueueManagement_AddPlaylist {
            get {
                return ResourceManager.GetString("QueueManagement_AddPlaylist", resourceCulture);
            }
        }
        
        public static string QueueManagement_AddTrack {
            get {
                return ResourceManager.GetString("QueueManagement_AddTrack", resourceCulture);
            }
        }
        
        public static string QueueManagement_ClearQueue {
            get {
                return ResourceManager.GetString("QueueManagement_ClearQueue", resourceCulture);
            }
        }
        
        public static string QueueManagement_TimeRemaining {
            get {
                return ResourceManager.GetString("QueueManagement_TimeRemaining", resourceCulture);
            }
        }
        
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Settings_AddFolder {
            get {
                return ResourceManager.GetString("Settings_AddFolder", resourceCulture);
            }
        }
        
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        public static string Settings_AutoImport {
            get {
                return ResourceManager.GetString("Settings_AutoImport", resourceCulture);
            }
        }
        
        public static string Settings_AutoImport_Info {
            get {
                return ResourceManager.GetString("Settings_AutoImport_Info", resourceCulture);
            }
        }
        
        public static string Settings_Automatic {
            get {
                return ResourceManager.GetString("Settings_Automatic", resourceCulture);
            }
        }
        
        public static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string Settings_ClearAll {
            get {
                return ResourceManager.GetString("Settings_ClearAll", resourceCulture);
            }
        }
        
        public static string Settings_Credits {
            get {
                return ResourceManager.GetString("Settings_Credits", resourceCulture);
            }
        }
        
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        public static string Settings_IntegrateDiscordRPC {
            get {
                return ResourceManager.GetString("Settings_IntegrateDiscordRPC", resourceCulture);
            }
        }
        
        public static string Settings_Integrations {
            get {
                return ResourceManager.GetString("Settings_Integrations", resourceCulture);
            }
        }
        
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        public static string Settings_License {
            get {
                return ResourceManager.GetString("Settings_License", resourceCulture);
            }
        }
        
        public static string Settings_Maintenance {
            get {
                return ResourceManager.GetString("Settings_Maintenance", resourceCulture);
            }
        }
        
        public static string Settings_MPRISShowCoverArt {
            get {
                return ResourceManager.GetString("Settings_MPRISShowCoverArt", resourceCulture);
            }
        }
        
        public static string Settings_MPRISShowCoverArt_Info {
            get {
                return ResourceManager.GetString("Settings_MPRISShowCoverArt_Info", resourceCulture);
            }
        }
        
        public static string Settings_PlaytimeLogging {
            get {
                return ResourceManager.GetString("Settings_PlaytimeLogging", resourceCulture);
            }
        }
        
        public static string Settings_Report {
            get {
                return ResourceManager.GetString("Settings_Report", resourceCulture);
            }
        }
        
        public static string Settings_ShowTimeInWindow {
            get {
                return ResourceManager.GetString("Settings_ShowTimeInWindow", resourceCulture);
            }
        }
        
        public static string Settings_ThankYou {
            get {
                return ResourceManager.GetString("Settings_ThankYou", resourceCulture);
            }
        }
        
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        public static string Settings_ViewLicense {
            get {
                return ResourceManager.GetString("Settings_ViewLicense", resourceCulture);
            }
        }
        
        public static string Settings_ViewSourceCode {
            get {
                return ResourceManager.GetString("Settings_ViewSourceCode", resourceCulture);
            }
        }
        
        public static string Settings_ViewWebsite {
            get {
                return ResourceManager.GetString("Settings_ViewWebsite", resourceCulture);
            }
        }
        
        public static string TagEditor {
            get {
                return ResourceManager.GetString("TagEditor", resourceCulture);
            }
        }
        
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        public static string TrackInfo {
            get {
                return ResourceManager.GetString("TrackInfo", resourceCulture);
            }
        }
        
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string FileFilter_AudioFiles {
            get {
                return ResourceManager.GetString("FileFilter_AudioFiles", resourceCulture);
            }
        }
        
        public static string FileFilter_Other {
            get {
                return ResourceManager.GetString("FileFilter_Other", resourceCulture);
            }
        }
    }
}
