//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRESHMusicPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRESHMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured: {0}.
        ///If you have the time, please report this to the devs at https://github.com/royce551/freshmusicplayer/issues.
        ///The log file they&apos;ll need is at {1}..
        /// </summary>
        public static string APPLICATION_CRITICALERROR {
            get {
                return ResourceManager.GetString("APPLICATION_CRITICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string CONTROLS_GOTO {
            get {
                return ResourceManager.GetString("CONTROLS_GOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Player.
        /// </summary>
        public static string CONTROLS_MINIPLAYER {
            get {
                return ResourceManager.GetString("CONTROLS_MINIPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause after current track.
        /// </summary>
        public static string CONTROLS_PAUSE_AFTTER_CURRENT_TRACK {
            get {
                return ResourceManager.GetString("CONTROLS_PAUSE_AFTTER_CURRENT_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folders.
        /// </summary>
        public static string IMPORT_BROWSE_FOLDERS {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for playlist files.
        /// </summary>
        public static string IMPORT_BROWSE_PLAYLIST {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for tracks.
        /// </summary>
        public static string IMPORT_BROWSE_TRACKS {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also drag and drop to this page..
        /// </summary>
        public static string IMPORT_DRAGDROP_PROMPT {
            get {
                return ResourceManager.GetString("IMPORT_DRAGDROP_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual file path/URL entry.
        /// </summary>
        public static string IMPORT_MANUALENTRY {
            get {
                return ResourceManager.GetString("IMPORT_MANUALENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string LIBRARY_ADD_TO_PLAYLIST {
            get {
                return ResourceManager.GetString("LIBRARY_ADD_TO_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue All.
        /// </summary>
        public static string LIBRARY_ENQUEUEALL {
            get {
                return ResourceManager.GetString("LIBRARY_ENQUEUEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Explorer.
        /// </summary>
        public static string LIBRARY_OPEN_FILEEXPLORER {
            get {
                return ResourceManager.GetString("LIBRARY_OPEN_FILEEXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        public static string LIBRARY_PLAYALL {
            get {
                return ResourceManager.GetString("LIBRARY_PLAYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string LYRICS {
            get {
                return ResourceManager.GetString("LYRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lyrics.
        /// </summary>
        public static string LYRICS_NOLYRICS {
            get {
                return ResourceManager.GetString("LYRICS_NOLYRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string MAINWINDOW_ALBUMS {
            get {
                return ResourceManager.GetString("MAINWINDOW_ALBUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string MAINWINDOW_ARTISTS {
            get {
                return ResourceManager.GetString("MAINWINDOW_ARTISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MAINWINDOW_IMPORT {
            get {
                return ResourceManager.GetString("MAINWINDOW_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Artist.
        /// </summary>
        public static string MAINWINDOW_NOARTIST {
            get {
                return ResourceManager.GetString("MAINWINDOW_NOARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Playing.
        /// </summary>
        public static string MAINWINDOW_NOTHINGPLAYING {
            get {
                return ResourceManager.GetString("MAINWINDOW_NOTHINGPLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A playback error occured:
        ///{0}
        ///We&apos;ll skip to the next track for you.
        /// </summary>
        public static string MAINWINDOW_PLAYBACK_ERROR_DETAILS {
            get {
                return ResourceManager.GetString("MAINWINDOW_PLAYBACK_ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string MAINWINDOW_PLAYLISTS {
            get {
                return ResourceManager.GetString("MAINWINDOW_PLAYLISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MAINWINDOW_SEARCH {
            get {
                return ResourceManager.GetString("MAINWINDOW_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MAINWINDOW_SETTINGS {
            get {
                return ResourceManager.GetString("MAINWINDOW_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MAINWINDOW_TRACKS {
            get {
                return ResourceManager.GetString("MAINWINDOW_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MENUBAR_EXIT {
            get {
                return ResourceManager.GetString("MENUBAR_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENUBAR_FILE {
            get {
                return ResourceManager.GetString("MENUBAR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Window.
        /// </summary>
        public static string MENUBAR_NEWWINDOW {
            get {
                return ResourceManager.GetString("MENUBAR_NEWWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MENUBAR_OPEN {
            get {
                return ResourceManager.GetString("MENUBAR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MENUBAR_SAVE {
            get {
                return ResourceManager.GetString("MENUBAR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tag Sources.
        /// </summary>
        public static string MENUBAR_TAGSOURCES {
            get {
                return ResourceManager.GetString("MENUBAR_TAGSOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared your library!.
        /// </summary>
        public static string NOTIFICATION_CLEARSUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_CLEARSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This playlist file could not be imported because one or more of the tracks could not be found.
        ///Missing File: {0}.
        /// </summary>
        public static string NOTIFICATION_COULD_NOT_IMPORT_PLAYLIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_COULD_NOT_IMPORT_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you tried to play, &quot;{0}&quot;, doesn&apos;t seem to exist..
        /// </summary>
        public static string NOTIFICATION_FILEGONE {
            get {
                return ResourceManager.GetString("NOTIFICATION_FILEGONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update....
        /// </summary>
        public static string NOTIFICATION_INSTALLINGUPDATE {
            get {
                return ResourceManager.GetString("NOTIFICATION_INSTALLINGUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library failed to load. Make sure that you don&apos;t have another instance of FMP running!.
        /// </summary>
        public static string NOTIFICATION_LIBRARYFAILED {
            get {
                return ResourceManager.GetString("NOTIFICATION_LIBRARYFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing after current track....
        /// </summary>
        public static string NOTIFICATION_PAUSING {
            get {
                return ResourceManager.GetString("NOTIFICATION_PAUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when updating: {0}.
        /// </summary>
        public static string NOTIFICATION_UPDATEERROR {
            get {
                return ResourceManager.GetString("NOTIFICATION_UPDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is ready to install! Restart FMP to apply the update..
        /// </summary>
        public static string NOTIFICATION_UPDATEREADY {
            get {
                return ResourceManager.GetString("NOTIFICATION_UPDATEREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string NOTIFICATIONS_CLEAR_ALL {
            get {
                return ResourceManager.GetString("NOTIFICATIONS_CLEAR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NOTIFICATIONS_TITLE {
            get {
                return ResourceManager.GetString("NOTIFICATIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Management.
        /// </summary>
        public static string PLAYLISTMANAGEMENT {
            get {
                return ResourceManager.GetString("PLAYLISTMANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string PLAYLISTMANAGEMENT_CREATE {
            get {
                return ResourceManager.GetString("PLAYLISTMANAGEMENT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PLAYLISTMANAGEMENT_EXPORT {
            get {
                return ResourceManager.GetString("PLAYLISTMANAGEMENT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do with &quot;{0}&quot;?.
        /// </summary>
        public static string PLAYLISTMANAGEMENT_HEADER {
            get {
                return ResourceManager.GetString("PLAYLISTMANAGEMENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string PLAYLISTMANAGEMENT_RENAME {
            get {
                return ResourceManager.GetString("PLAYLISTMANAGEMENT_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string QUEUEMANAGEMENT_ADDPLAYLIST {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_ADDPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        public static string QUEUEMANAGEMENT_ADDTRACK {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_ADDTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string QUEUEMANAGEMENT_CLEARQUEUE {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_CLEARQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QUEUEMANAGEMENT_QUEUEHEADER {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_QUEUEHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time - .
        /// </summary>
        public static string QUEUEMANAGEMENT_REMAININGTIME {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_REMAININGTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SETTINGS_ABOUT {
            get {
                return ResourceManager.GetString("SETTINGS_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SETTINGS_APPEARANCE {
            get {
                return ResourceManager.GetString("SETTINGS_APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update Mode.
        /// </summary>
        public static string SETTINGS_AUTOUPDATEMODE {
            get {
                return ResourceManager.GetString("SETTINGS_AUTOUPDATEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and update library.
        /// </summary>
        public static string SETTINGS_CLEANLIBRARY {
            get {
                return ResourceManager.GetString("SETTINGS_CLEANLIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Squid Grill (and open source contributors)
        ///Licensed under GPL v3
        ///Thank you for using FRESHMusicPlayer! ♥.
        /// </summary>
        public static string SETTINGS_CREDITS {
            get {
                return ResourceManager.GetString("SETTINGS_CREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SETTINGS_GENERAL {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import library from old FMP.
        /// </summary>
        public static string SETTINGS_IMPORTOLDFMP {
            get {
                return ResourceManager.GetString("SETTINGS_IMPORTOLDFMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string SETTINGS_INTEGRATION {
            get {
                return ResourceManager.GetString("SETTINGS_INTEGRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SETTINGS_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string SETTINGS_MAINTENANCE {
            get {
                return ResourceManager.GetString("SETTINGS_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to irreversibly clear your library. Are you sure?.
        /// </summary>
        public static string SETTINGS_NUKE_LIBRARY_WARNING {
            get {
                return ResourceManager.GetString("SETTINGS_NUKE_LIBRARY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuke library.
        /// </summary>
        public static string SETTINGS_NUKELIBRARY {
            get {
                return ResourceManager.GetString("SETTINGS_NUKELIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Tracking.
        /// </summary>
        public static string SETTINGS_PLAYBACKTRACKING {
            get {
                return ResourceManager.GetString("SETTINGS_PLAYBACKTRACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get pre-release versions of FMP.
        /// </summary>
        public static string SETTINGS_PRERELEASE {
            get {
                return ResourceManager.GetString("SETTINGS_PRERELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset configuration to defaults.
        /// </summary>
        public static string SETTINGS_RESET {
            get {
                return ResourceManager.GetString("SETTINGS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to be applied, FMP needs to restart..
        /// </summary>
        public static string SETTINGS_RESTART_NEEDED_PROMPT {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_NEEDED_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        public static string SETTINGS_RESTART_NOW {
            get {
                return ResourceManager.GetString("SETTINGS_RESTART_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the way FMP behaves.
        /// </summary>
        public static string SETTINGS_SUBHEADER {
            get {
                return ResourceManager.GetString("SETTINGS_SUBHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SETTINGS_THEME {
            get {
                return ResourceManager.GetString("SETTINGS_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SETTINGS_THEME_DARK {
            get {
                return ResourceManager.GetString("SETTINGS_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SETTINGS_THEME_LIGHT {
            get {
                return ResourceManager.GetString("SETTINGS_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time instead of title in window title.
        /// </summary>
        public static string SETTINGS_TIMEWINDOWTITLE {
            get {
                return ResourceManager.GetString("SETTINGS_TIMEWINDOWTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string SETTINGS_UPDATES {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string SETTINGS_UPDATES_AUTO {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATES_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string SETTINGS_UPDATES_MANUAL {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATES_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt before updating.
        /// </summary>
        public static string SETTINGS_UPDATES_PROMPT {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATES_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates now.
        /// </summary>
        public static string SETTINGS_UPDATESCHECKNOW {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATESCHECKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked {0}.
        /// </summary>
        public static string SETTINGS_UPDATESLASTCHECKED {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATESLASTCHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Editor.
        /// </summary>
        public static string TAGEDITOR {
            get {
                return ResourceManager.GetString("TAGEDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string TAGEDITOR_ALBUMARTIST {
            get {
                return ResourceManager.GetString("TAGEDITOR_ALBUMARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string TAGEDITOR_ARTIST {
            get {
                return ResourceManager.GetString("TAGEDITOR_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be applied when you play a new track..
        /// </summary>
        public static string TAGEDITOR_BACKGROUNDSAVE {
            get {
                return ResourceManager.GetString("TAGEDITOR_BACKGROUNDSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change File....
        /// </summary>
        public static string TAGEDITOR_CHANGEFILE {
            get {
                return ResourceManager.GetString("TAGEDITOR_CHANGEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string TAGEDITOR_COMPOSER {
            get {
                return ResourceManager.GetString("TAGEDITOR_COMPOSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Art.
        /// </summary>
        public static string TAGEDITOR_COVERART {
            get {
                return ResourceManager.GetString("TAGEDITOR_COVERART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Number.
        /// </summary>
        public static string TAGEDITOR_DISCNUM {
            get {
                return ResourceManager.GetString("TAGEDITOR_DISCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing .
        /// </summary>
        public static string TAGEDITOR_EDITINGHEADER {
            get {
                return ResourceManager.GetString("TAGEDITOR_EDITINGHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple search results for this album. Which one do you want?.
        /// </summary>
        public static string TAGEDITOR_INTEGRATIONDISAMBIGUATION {
            get {
                return ResourceManager.GetString("TAGEDITOR_INTEGRATIONDISAMBIGUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cover art present.
        /// </summary>
        public static string TAGEDITOR_NOCOVERART {
            get {
                return ResourceManager.GetString("TAGEDITOR_NOCOVERART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t connected to the internet :(.
        /// </summary>
        public static string TAGEDITOR_NOINTERNET {
            get {
                return ResourceManager.GetString("TAGEDITOR_NOINTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for this album :(.
        /// </summary>
        public static string TAGEDITOR_NORESULTS {
            get {
                return ResourceManager.GetString("TAGEDITOR_NORESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TAGEDITOR_SAVE {
            get {
                return ResourceManager.GetString("TAGEDITOR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes to {0}?.
        /// </summary>
        public static string TAGEDITOR_SAVECHANGES {
            get {
                return ResourceManager.GetString("TAGEDITOR_SAVECHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TAGEDITOR_TITLE {
            get {
                return ResourceManager.GetString("TAGEDITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Number.
        /// </summary>
        public static string TAGEDITOR_TRACKNUM {
            get {
                return ResourceManager.GetString("TAGEDITOR_TRACKNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string TRACKINFO_ALBUM {
            get {
                return ResourceManager.GetString("TRACKINFO_ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Info.
        /// </summary>
        public static string TRACKINFO_ALBUMINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_ALBUMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string TRACKINFO_BITRATE {
            get {
                return ResourceManager.GetString("TRACKINFO_BITRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string TRACKINFO_DISCNUMBER {
            get {
                return ResourceManager.GetString("TRACKINFO_DISCNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string TRACKINFO_GENRE {
            get {
                return ResourceManager.GetString("TRACKINFO_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Info.
        /// </summary>
        public static string TRACKINFO_TECHNICALINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_TECHNICALINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Info.
        /// </summary>
        public static string TRACKINFO_TRACKINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_TRACKINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string TRACKINFO_TRACKNUMBER {
            get {
                return ResourceManager.GetString("TRACKINFO_TRACKNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TRACKINFO_YEAR {
            get {
                return ResourceManager.GetString("TRACKINFO_YEAR", resourceCulture);
            }
        }
    }
}
