//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRESHMusicPlayer_WPF_UI_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRESHMusicPlayer_WPF_UI_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured: {0}.
        ///If you have the time, please report this to the devs at https://github.com/royce551/freshmusicplayer/issues.
        ///The log file they&apos;ll need is at {1}..
        /// </summary>
        public static string APPLICATION_CRITICALERROR {
            get {
                return ResourceManager.GetString("APPLICATION_CRITICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folders.
        /// </summary>
        public static string IMPORT_BROWSE_FOLDERS {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for playlist files.
        /// </summary>
        public static string IMPORT_BROWSE_PLAYLIST {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for tracks.
        /// </summary>
        public static string IMPORT_BROWSE_TRACKS {
            get {
                return ResourceManager.GetString("IMPORT_BROWSE_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also drag and drop to this page..
        /// </summary>
        public static string IMPORT_DRAGDROP_PROMPT {
            get {
                return ResourceManager.GetString("IMPORT_DRAGDROP_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string MAINWINDOW_ALBUMS {
            get {
                return ResourceManager.GetString("MAINWINDOW_ALBUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string MAINWINDOW_ARTISTS {
            get {
                return ResourceManager.GetString("MAINWINDOW_ARTISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MAINWINDOW_IMPORT {
            get {
                return ResourceManager.GetString("MAINWINDOW_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Artist.
        /// </summary>
        public static string MAINWINDOW_NOARTIST {
            get {
                return ResourceManager.GetString("MAINWINDOW_NOARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///We&apos;ll skip to the next track for you.
        /// </summary>
        public static string MAINWINDOW_PLAYBACK_ERROR_DETAILS {
            get {
                return ResourceManager.GetString("MAINWINDOW_PLAYBACK_ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MAINWINDOW_SETTINGS {
            get {
                return ResourceManager.GetString("MAINWINDOW_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string MAINWINDOW_TRACKS {
            get {
                return ResourceManager.GetString("MAINWINDOW_TRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MENUBAR_EXIT {
            get {
                return ResourceManager.GetString("MENUBAR_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENUBAR_FILE {
            get {
                return ResourceManager.GetString("MENUBAR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Window.
        /// </summary>
        public static string MENUBAR_NEWWINDOW {
            get {
                return ResourceManager.GetString("MENUBAR_NEWWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MENUBAR_OPEN {
            get {
                return ResourceManager.GetString("MENUBAR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MENUBAR_SAVE {
            get {
                return ResourceManager.GetString("MENUBAR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tag Sources.
        /// </summary>
        public static string MENUBAR_TAGSOURCES {
            get {
                return ResourceManager.GetString("MENUBAR_TAGSOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing File.
        /// </summary>
        public static string NOTIFICATION_COULD_NOT_IMPORT_PLAYLIST {
            get {
                return ResourceManager.GetString("NOTIFICATION_COULD_NOT_IMPORT_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string NOTIFICATIONS_CLEAR_ALL {
            get {
                return ResourceManager.GetString("NOTIFICATIONS_CLEAR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NOTIFICATIONS_TITLE {
            get {
                return ResourceManager.GetString("NOTIFICATIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Playlist.
        /// </summary>
        public static string QUEUEMANAGEMENT_ADDPLAYLIST {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_ADDPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        public static string QUEUEMANAGEMENT_ADDTRACK {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_ADDTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string QUEUEMANAGEMENT_CLEARQUEUE {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_CLEARQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QUEUEMANAGEMENT_QUEUEHEADER {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_QUEUEHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time - .
        /// </summary>
        public static string QUEUEMANAGEMENT_REMAININGTIME {
            get {
                return ResourceManager.GetString("QUEUEMANAGEMENT_REMAININGTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist - .
        /// </summary>
        public static string TAGEDITOR_ALBUMARTIST {
            get {
                return ResourceManager.GetString("TAGEDITOR_ALBUMARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist - .
        /// </summary>
        public static string TAGEDITOR_ARTIST {
            get {
                return ResourceManager.GetString("TAGEDITOR_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be applied when you play a new track..
        /// </summary>
        public static string TAGEDITOR_BACKGROUNDSAVE {
            get {
                return ResourceManager.GetString("TAGEDITOR_BACKGROUNDSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change File....
        /// </summary>
        public static string TAGEDITOR_CHANGEFILE {
            get {
                return ResourceManager.GetString("TAGEDITOR_CHANGEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer - .
        /// </summary>
        public static string TAGEDITOR_COMPOSER {
            get {
                return ResourceManager.GetString("TAGEDITOR_COMPOSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Number - .
        /// </summary>
        public static string TAGEDITOR_DISCNUM {
            get {
                return ResourceManager.GetString("TAGEDITOR_DISCNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing .
        /// </summary>
        public static string TAGEDITOR_EDITINGHEADER {
            get {
                return ResourceManager.GetString("TAGEDITOR_EDITINGHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TAGEDITOR_SAVE {
            get {
                return ResourceManager.GetString("TAGEDITOR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes to {0}?.
        /// </summary>
        public static string TAGEDITOR_SAVECHANGES {
            get {
                return ResourceManager.GetString("TAGEDITOR_SAVECHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title - .
        /// </summary>
        public static string TAGEDITOR_TITLE {
            get {
                return ResourceManager.GetString("TAGEDITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Number - .
        /// </summary>
        public static string TAGEDITOR_TRACKNUM {
            get {
                return ResourceManager.GetString("TAGEDITOR_TRACKNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album - .
        /// </summary>
        public static string TRACKINFO_ALBUM {
            get {
                return ResourceManager.GetString("TRACKINFO_ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Info.
        /// </summary>
        public static string TRACKINFO_ALBUMINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_ALBUMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate - .
        /// </summary>
        public static string TRACKINFO_BITRATE {
            get {
                return ResourceManager.GetString("TRACKINFO_BITRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc  .
        /// </summary>
        public static string TRACKINFO_DISCNUMBER {
            get {
                return ResourceManager.GetString("TRACKINFO_DISCNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre - .
        /// </summary>
        public static string TRACKINFO_GENRE {
            get {
                return ResourceManager.GetString("TRACKINFO_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Info.
        /// </summary>
        public static string TRACKINFO_TECHNICALINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_TECHNICALINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Info.
        /// </summary>
        public static string TRACKINFO_TRACKINFO {
            get {
                return ResourceManager.GetString("TRACKINFO_TRACKINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track .
        /// </summary>
        public static string TRACKINFO_TRACKNUMBER {
            get {
                return ResourceManager.GetString("TRACKINFO_TRACKNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year - .
        /// </summary>
        public static string TRACKINFO_YEAR {
            get {
                return ResourceManager.GetString("TRACKINFO_YEAR", resourceCulture);
            }
        }
    }
}
